### ISSUE TITLE
Join endpoint is vulnerable to SQL injection

### ISSUE THREAD

**Issue by mjvmroz** [floor-thirteen/ddong-server#4]
We either need to standardise a system of sanitising, or rely on an existing one in some kind of ORM. My vote is on the latter.

**Comment by tristanHessell** [comment]
I was under the impression that the prepared statement voided SQL injection vulnerabilities. Have you actually tested this out?

Either way, I agree to utilise an ORM moving forward

**Comment by mjvmroz** [comment]
My mistake - at a glance, I believed it just to be a string format. But yeah, I think ORMs are good. Inline SQL always seems pretty messy and adds a lot of boilerplate.
